#!/usr/bin/env bash

# Fix file mtime to match last git commit date

set -o errexit -o pipefail -o noglob -o noclobber -o nounset
IFS=$'\n\t'

# shellcheck disable=SC2016
git ls-tree -z -r --name-only HEAD | parallel --gnu --null --quote sh -c '
  mtime=$(git log --date=iso -1 --format=%cd "{}");
  touch --date "$mtime" "{}";
  echo "$mtime - {}"
'
