#!/usr/bin/env bash

# Fix file mtime to match last git commit date

set -o errexit -o pipefail -o noglob -o noclobber -o nounset
IFS=$'\n\t'

git ls-tree -z -r --name-only HEAD | parallel --null --quote sh -c '
  mtime=$(git log --date=local -1 --format=%cd "{}");
  touch --date "$mtime" "{}";
  echo "$mtime - {}"
'
