#!/usr/bin/env bash

# Prune all merged local and remote branches

set -feuo pipefail
IFS=$'\n\t'

branch=$(git rev-parse --abbrev-ref HEAD)
remote=$(git config -- "branch.${branch}.remote")

git remote update --prune > /dev/null

# TODO: simplify this if possible
git branch --remotes --merged "$remote/$branch" \
  | grep "^\s*$remote/" \
  | sed "s/^\s*$remote\///" \
  | grep -v "^HEAD\b" \
  | grep -v "^$branch$" \
  | xargs --no-run-if-empty --max-args 1 git push --delete -- "$remote"
