#!/usr/bin/env bash

# Fix file mtime to match last git commit date

set -o errexit -o pipefail -o noglob -o noclobber -o nounset
IFS=$'\n\t'

git ls-tree -z -r --name-only HEAD | while read -r -d $'\0' file; do
  mtime=$(git log --date=local -1 --format=%cd "$file")
  touch --date "$mtime" "$file"
  echo "$mtime - $file"
done
