#!/usr/bin/env bash

# Fix branch commit data to be the same as author data

set -feuo pipefail
IFS=$'\n\t'

parent=${1-master}

# The command to execute for each commit
read -r -d '' command <<-'COMMAND' || true
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"
COMMAND

# Rebase the current branch on top of the parent
git rebase -- "$parent"

# Rewrite all commits to use the author data
git filter-branch --force --env-filter "$command" -- "$parent..HEAD"
